### PR TITLE
Adding diKTat (Kotlin linter) to the list

### PR DESCRIPTION
**Pull request by akuleshov7**
### What is diKTat:
1) DiKTat is a formal and strict code style for Kotlin with implementation in a linter.
2) DiKTat is a collection of Kotlin code style rules implemented as AST visitors on top of KTlint framework. This linter can validate (check) and automatically fix (format) the code. The set of rules (visitors) is bigger than in ktlint standard set of rules (~100 inspections already). All rules are highly configurable.
3) DiKTat is used to detect (and partially fix) code-style issues, codesmells and bugs in code. And comparing to other linters - it has a very strict and properly documented code-style that it is implementing. But anyway gives a chance to configure or suppress inspections (from code or using configuration file).
4) DiKTat can be run with it's own maven plugin/gradle plugin/cli
5) DiKTat has been added to awesome-kotlin list:
   https://github.com/KotlinBy/awesome-kotlin/blob/readme/README.md#tools-back-

### CODE REVIEW

**Comment by mre** [comment]
Nice tool. We should add it.
The `README.md` is actually rendered from the `data` folder. Can you add a new YAML file at https://github.com/analysis-tools-dev/static-analysis/tree/master/data/tools to add the tool instead? 😅

**Comment by akuleshov7** [comment]
> Nice tool. We should add it.
> The `README.md` is actually rendered from the `data` folder. Can you add a new YAML file at https://github.com/analysis-tools-dev/static-analysis/tree/master/data/tools to add the tool instead? 😅

updated :D  if you will merge - please squash commits as I have not amended them

**Comment by mre** [comment]
Merged. Thanks for the PR @akuleshov7. 👍

**Comment by mre** [comment]
Entry is [live now](https://analysis-tools.dev/tool/diktat). 🥳 
@akuleshov7 would you mind adding your first comment to the comments section of that page? It's valuable information that could help people make an informed decision about the tool.

**Comment by akuleshov7** [comment]
> Entry is [live now](https://analysis-tools.dev/tool/diktat). 🥳
> @akuleshov7 would you mind adding your first comment to the comments section of that page? It's valuable information that could help people make an informed decision about the tool.

oh, I don't see where to add...

**Comment by mre** [comment]
Thanks! Nicely done. ⭐

**Pull request merged**
