### PR TITLE
Fix some broken internal link in the Readme

### LINKED ISSUE #1439: Many links in the table of contents are not working
Hi.

Some links in the table of contents are broken, for example:
* [C++](https://github.com/analysis-tools-dev/static-analysis#cpp)
* [.env](https://github.com/analysis-tools-dev/static-analysis#dotenv)
* [Configuration Management](https://github.com/analysis-tools-dev/static-analysis#configmanagement)

This is because the anchor link generated for "C++" isn't "cpp" but "c-2".

### PR DESCRIPTION
**Pull request by Delgan**
Fix #1439.

* [x] I have not changed the `README.md` directly.

### CODE REVIEW

**Comment by mre** [comment]
Looks good! The CI failure was to be expected. It is a safety measure against unwanted direct modifications when adding new tools. In this case, it's fine, of course.

**Comment by mre** [comment]
It renders correctly, but it doesn't seem to work for me. The C++ tag points to the top of the file. Weird.

**Comment by Delgan** [comment]
> It renders correctly, but it doesn't seem to work for me. The C++ tag points to the top of the file. Weird.

Oh, really? I was going to post to say that it worked great on my computer.
I'm using Firefox, although I'm surprised it matters at all.

**Comment by mre** [comment]
Just checked again and it works on my laptop now. Yesterday I tried on the GitHub app on mobile (Android) and the links to C# and C++ don't work while the rest does work. (Tried again and that's still the case).
It works on Firefox mobile, though, so I think we're good! 

Glad you managed to power through and fix this! ⭐

**Pull request merged**
