### PR TITLE
Remove "deprecated" for jshint

### PR DESCRIPTION
**Pull request by AristoChen**
I found the latest commit of this repo was about a month ago, so I guess that should be considerd as still maintaining?

### CODE REVIEW

**Comment by mre** [comment]
There is a longer discussion [here](https://github.com/analysis-tools-dev/static-analysis/issues/223) about the reasons.
I think `deprecated` is not the correct term here. As you point out, the tool is still receiving updates. I'm rather looking for a term to express "not recommended for new projects by the community". Maybe we could use `discussion` and link to the discussion issue? Opinions?

**Comment by AristoChen** [comment]
Wow, I didn't realize that there was a long discussion about ```deprecated```.

I agree that ```deprecated``` may not be a proper term in this case, maybe ```discussion``` would be a relatively proper term.

In my opinion, maybe we can modify the definition of ```deprecated```? maybe use this term to indicate that a repo meets the following criteria
- Repo was not maintained for longer than half a year
- Repo was archived
- etc

And ```discussion``` may be used to indicate that a repo is not recommended by the community, and we can link to the discussion issue.

**Comment by mre** [comment]
Good points.
Would you mind adding a `discussion` field (similar to to the `source` field) to both the Rust rendering code and the `tools.yml`? Similar to this commit: https://github.com/analysis-tools-dev/static-analysis/commit/2df2790dd26306de0141c5890ba38677e5ee3dfb (Please ignore the changes in `tools.yml`. I went on a rampage there and fixed some inaccuracies.)
The `deprecated` field can stay, but I'd add the discussion links in the next step where needed.

Thanks for your ongoing support @AristoChen. Much appreciated!

**Comment by AristoChen** [comment]
I added ```discussion``` field, if there is anything that I did wrong or anthing else you want me to do, please let me know :)

**Comment by mre** [comment]
Thanks!
We should make it clear that there was a debate from the rendered `README.md`.
I wonder if we can have an `:information_source:` (ℹ️) button next to the entry that links to the discussion.
Would you be able to add that?

**Comment by AristoChen** [comment]
Added, does that meet you expectation?

**Comment by mre** [comment]
Perfect! Thanks so much @AristoChen. You rock! 🎸

**Pull request merged**
