### PR TITLE
Create an optional `resources` section with links to videos and articles.

### PR DESCRIPTION
**Pull request by mre**
Some entries can be enriched with external links.
These can be websites, PDFs, or videos.
This PR adds support for an optional `resources` field.
For now we only plan to use it on the website as the
rendering on the `README.md` could get a little cluttered.
Nevertheless I think it's a good idea to keep all data
in the repo.

### CODE REVIEW

**Comment by AristoChen** [comment]
LGTM !

I will add to entry if I found some useful `resource` in the future

**Comment by mre** [comment]
Thanks for the feedback @AristoChen. 🥳

**Comment by jakubsacha** [comment]
I'm wondering if it would make sense to add type to the resource entries. That way we could embed youtube videos, but also link to valuable blog posts etc.

**Comment by mre** [comment]
Yeah that would help us group and categorize the resources easily. On the other hand it's another thing to remember when adding a new resource. The way we handle it on the website is assuming everything containing youtube in the url is a video. The rest are just normal links.

**Pull request merged**
