### PR TITLE
chore: add one more static type checker for JavaScript.

### PR DESCRIPTION
**Pull request by JSMonk**

### CODE REVIEW

**Comment by mre** [comment]
Hey @JSMonk,
the tool looks great and I'm looking forward to adding it.
Could you add it to `data/data.yml` instead? We recently changed the format to be machine-readable. More info in the [contributing guidelines](https://github.com/analysis-tools-dev/static-analysis/blob/master/CONTRIBUTING.md#format).
Thanks! 😊

**Comment by mre** [comment]
Thanks! Fixed a typo and I hope it's fine now. BTW, I can't reach the homepage at the moment.
Get redirected to http://hegel.js.org, which can't be opened in Firefox/Chrome on my side.
Maybe it has something to do with this change? https://github.com/JSMonk/hegel/commit/37159e9e0bfa3651055fae55dd860521a3ac113a

**Comment by JSMonk** [comment]
@mre, currently we changed the location of the webpage and waiting for the js.org adding our project as subdomain :)

**Comment by mre** [comment]
Ah alright. Merging :)

**Pull request merged**
