### PR TITLE
Add SQLFluff

### PR DESCRIPTION
**Pull request by kochalex**
Adds [SQLFluff](https://github.com/sqlfluff/sqlfluff), a sql linter and formatter with 368 stars.

### CODE REVIEW

**Comment by mre** [comment]
Thanks a lot @kochalex. 🐕

**Comment by mre** [comment]
(Really cool blog domain name btw.)

**Comment by kochalex** [comment]
> (Really cool blog domain name btw.)

Thanks, I should really do something with that...

**Comment by mre** [comment]
> Thanks, I should really do something with that...

Yes. It would be a waste otherwise. 😆 
Check this out for inspiration: https://github.com/topics/portfolio-template

**Pull request merged**
