### PR TITLE
Fix link issue

### PR DESCRIPTION
**Pull request by AristoChen**

### CODE REVIEW

**Comment by mre** [comment]
Hey @AristoChen,
the anchors are auto-generated using the render code [here](https://github.com/analysis-tools-dev/static-analysis/tree/master/data/render).
I guess we have to make some adjustments to the code to fix it.
If you want, you can give it a shot; otherwise I'll have a look when I find some time.

**Comment by AristoChen** [comment]
I see, I will do that, thanks for your suggestion :)

**Comment by AristoChen** [comment]
Hi,

I made some adjustment, and the result is what I expected.

I am very very new to rust language, so if there is anything that I didn’t make it right, please let me know, I will do my best to fix it.

**Comment by mre** [comment]
Thanks for your PR. Looks great! Tested locally and it works. Merging. 🚢 🇮🇹 

> I am very very new to rust language
I'm impressed by how quickly you learn.

**Pull request merged**
