### PR TITLE
Add mythril and mythx analysis tools

### PR DESCRIPTION
**Pull request by JoranHonig**
Hi 👋 thanks for this awesome project.

In this pr I've added two related SAST tools:
- https://github.com/ConsenSys/mythril
- https://mythx.io

Let me know if there is okay like this 👌

### CODE REVIEW

**Comment by mre** [comment]
Hey @JoranHonig,
thanks for adding those tools.
I added the `proprietary` tag to MythX, as it seems to be a proprietary platform. Correct me if I'm wrong.
Also the introduction of a `smart-contracts` makes a lot of sense to me. I got rid of the old `solidity` tag to make the category more general. Any objections?

**Comment by JoranHonig** [comment]
> I added the proprietary tag to MythX, as it seems to be a proprietary platform. Correct me if I'm wrong.

You are completely right! Sorry about that, I thought I put it there 😅

**Comment by JoranHonig** [comment]
> Also the introduction of a smart-contracts makes a lot of sense to me. I got rid of the old solidity tag to make the category more general. Any objections?

I have no strong feelings about this. I just wanna note that it could be that a smart contract is not written in Solidity.

**Comment by mre** [comment]
> I just wanna note that it could be that a smart contract is not written in Solidity.

Yeah that's kind of the poing. 😅 Before there was no way to express smart contracts not being written in Solidity. Now we group everything under the `smart-contract` tag to make other smart contracts possible. 😉

**Comment by mre** [comment]
Merged now. Thanks again for your contribution @JoranHonig. 🥳

**Pull request merged**
