### PR TITLE
Added links to scan - a free oss tool

### PR DESCRIPTION
**Pull request by prabhu**

### CODE REVIEW

**Comment by mre** [comment]
Hey @prabhu,
thanks for the PR.
Waiting a bit until the tool reaches 20 stars as per our [contribution guidelines](https://github.com/analysis-tools-dev/static-analysis/blob/master/CONTRIBUTING.md).
Also, the format would have to be changed: tools have to be added to `data/data.yml` and not directly to the `README.md` anymore. 😉

**Comment by prabhu** [comment]
Thank you for your prompt response. I think the project has reached the needed 20 stars (What does a star mean btw?). But the yaml file looks a bit overwhelming so need time to take a look and update it correctly.

**Comment by mre** [comment]
Hey @prabhu,
you're correct. Sorry for the late response.
We can add your tool now. ⭐ Refactored the tools.yaml a bit, so maybe you can have another look and give it a try? I could do it, too but I'm hoping for some feedback to see if the structure of the file is understandable and what we could do to improve the user-experience. What do you think?

**Comment by mre** [comment]
@prabhu any update here?

**Comment by mre** [comment]
Added in #446.

**Pull request closed without merging**
