### PR TITLE
Fix homepage of jsonhint

### PR DESCRIPTION
**Pull request by AristoChen**
Hi, I found this homepage link is wrong, so i replace it with another one

### CODE REVIEW

**Comment by mre** [comment]
Thanks for the pull request. I just noticed that you modified the `README.md` directly. This is a common problem and we have to make it clearer that this is the wrong place for edits not. 😅
The real place is is `data/tools.yaml` now. Can you make the change, there instead?
Thanks!

**Comment by AristoChen** [comment]
Hi, 

To be honest, I do just modify ```data/tools.yml```, and I didn't do anything with ```README.md``` at all

Here is my local change log

image

As you can see, the newest commit is to modify homepage of jshint, and I didn't create the second commit which modified ```README.md```. It seems that it was automatically commited by the Analysis Tools Bot

I did ```git push -f``` just now. but there is still another commit automatically commited by the Analysis Tools Bot

**Comment by mre** [comment]
Alright, forgot about our bot, sorry.

**Comment by mre** [comment]
Thanks for the fix :)

**Pull request merged**
