### PR TITLE
Add star count badges to github repos (partial)

### PR DESCRIPTION
**Pull request by Amar1729**
#327 

Added star count badges to all the tools in the `Python` section to see how it looks. To be honest it does end up looking a little busy. Also, I'm not really sure about the API limits of shields.io - even though loading one section works, it may have trouble if the entire readme has these badges (~330 github links currently) on a page load.

Link to see the readme on my fork: https://github.com/amar1729/static-analysis/#python

### CODE REVIEW

**Comment by mre** [comment]
Thanks for your work @Amar1729. I have to say this information is quite helpful when comparing different tools. 
The data format has changed a bit. The `README.md` is actually rendered from the list of tools  in [data.yml](https://github.com/analysis-tools-dev/static-analysis/blob/master/data/data.yml). 
We could extend this structure per entry so that we have a separate "source" URL that points to Gitlab/Github next to the homepage URL like so:

```yaml
- name: My awesome tool
  homepage: "https://example.com/"
  source: "https://github.com/example/awesome"
  description: "Awesome description"
  tags:
    - foo
    - bar
```

Of course, many tools don't have a dedicated homepage, so the homepage URL would be the same as the source URL. Others are proprietary, so the source URL would be empty. That's fine in my book, as the two URLs would serve a different purpose.

We can then auto-generate the README from the template [here](https://github.com/analysis-tools-dev/static-analysis/tree/master/data/render/src/templates).
The shields could be linked there. To make it look less busy, you can style the shields a bit. [Here](https://img.shields.io/github/stars/PyCQA/bandit?style=flat-square&color=ccc) is an example:



As a final step, we could add the star counter to the [new website](https://analysis-tools.dev/) by calling the Github API with the information from the `source` URL.  
Sounds like a plan?

**Comment by Amar1729** [comment]
@mre ah I didn't even notice the README was being rendered from somewhere else. I think that having that `source` separate from the homepage makes sense (I know Homebrew and pypi.org keep that info separate, for example).

Do you think it makes sense to have a separate `linter.badge` entry in data.yml, so the README templating can just use that? Then any non-github sources will just have an empty `badge` attribute as well.

And yeah, displaying these badges on the website sounds like a good idea.

**Comment by mre** [comment]
> Do you think it makes sense to have a distinct linter.badge entry in data.yml, so the README templating can just use that? Then any non-github sources will just have an empty badge attribute as well.

Yeah sure we could add that. If we find batches for Gitlab in the future, too then that would be the perfect place. As you said, if we find no good fit it'll simple be missing from the entry. 👍

**Comment by mre** [comment]
@Amar1729 as a heads-up we refactored the tools list lately, so you'd have to reintegrate master if you're planning to work on adding the fields we talked about. Wonder if we should create a new branch for that and create a fresh pull request. What do you think?

**Comment by Amar1729** [comment]
Sounds good. I'll take a look at the new PR and the `additional-fields` branch for adding badges; will open a new PR based off of that in a few days.

**Comment by Amar1729** [comment]
Closed in favor of new pr

**Pull request closed without merging**
