### PR TITLE
Add relint to multiple language tools

### PR DESCRIPTION
**Pull request by codingjoe**

### CODE REVIEW

**Comment by mre** [comment]
Thanks for your contribution @codingjoe. The tool looks nice but before merging I'll give it some more time to get a bit more popular (20 stars is the new threshold for additions).
I'll revisit this in the future.

**Comment by mre** [comment]
Noticed that relint reached 21 stars and 4 contributors now. 🎉 
@codingjoe if you want you can update the PR to add it. Note that tools now get added in `tools.yml` instead of the `README.md` directly.

**Comment by codingjoe** [comment]
@mre thanks, I updated my submission. However, I am struggling with the tags, since the linter works for any and all programming languages.

**Comment by mre** [comment]
In the beginning, we had a `multi` tag for tools that supported multiple languages. I removed it, because having a list of tags with more than one entry was already covering that case.
Admittedly, supporting any and all programming languages is a special case.
We could introduce an `any` tag to express that. What do you think? 🤔 
If that sounds like a good idea to you, please add the `any` tag to `tags.yml` and use it for your tool.

**Comment by mre** [comment]
Sounds very reasonable to me. Thanks for the explanation. Merged!

**Pull request merged**
