### PR TITLE
Add Mega-Linter + language & formats tags

### PR DESCRIPTION
**Pull request by nvuillam**
Added [Mega-Linter](https://nvuillam.github.io/mega-linter/) in the list

There were missing tags so I added them too :)

### CODE REVIEW

**Comment by mre** [comment]
Thanks @nvuillam. 👍

**Comment by nvuillam** [comment]
@mre Thanks to you for validating the PR :)
I'll try to add the other linters I used that I didn't see in the list yet ^^

If you need icons for the languages I added, you can pick them there :)
https://github.com/nvuillam/mega-linter/tree/master/docs/assets/icons

**Comment by mre** [comment]
>  I'll try to add the other linters I use in Mega-Linter and that I didn't see in static-analysis list yet ^^

Oh that would be great. Thanks!

> If you need icons for the languages/formats I added, you can pick them there :)

Wow, a nice collection. We need SVG icons for the website, but this could still be a nice source of reference.

**Comment by nvuillam** [comment]
I took most of my icons on https://icon-icons.com/ , you can download them as svg there and they are free :)

**Comment by mre** [comment]
Nice! Will do, thanks!

**Comment by nvuillam** [comment]
:)
Anyway... analysis-tools.dev is a great project, I'll sure browse the site to select the next linters i'll add ;)

ps: I looked on analysis-tools on twitter but didn't find an account... so just named the site :)
https://twitter.com/NicolasVuillamy/status/1348600553727782912

**Comment by mre** [comment]
Yeah we don't have a Twitter account. [@AnalysisTools](https://twitter.com/AnalysisTools) was suspended and not available for registration, AnalysisToolsDev was longer than the maximum 15 characters, and everything else didn't make much sense. 🤷‍♀️ I'll retweet from my account. Thanks for the mention.

**Comment by nvuillam** [comment]
No problem, gotta support each other between code quality lovers ( unfortunately we are not so many.... 🤣 )

**Pull request merged**
