### PR TITLE
Add PHP CI tool: shipmonk/composer-dependency-analyser

### PR DESCRIPTION
**Pull request by janedbal**
* [x] I have not changed the `README.md` directly.

* Homepage: https://github.com/shipmonk-rnd/composer-dependency-analyser

### CODE REVIEW

**Comment by mre** [comment]
We haven't had emojis in the description before, and I don't know how I feel about it, but let's give it a shot. There's a chance that we'll remove them if they cause any issues. Just a heads-up. 😉

**Comment by mre** [comment]
Thanks for the addition, @janedbal. ⭐

**Comment by janedbal** [comment]
When can I expect this tool to show in https://analysis-tools.dev/ so that I can check the emojis?

**Comment by mre** [comment]
Noticed that we didn't take changes to the `tools.json` file into account, which gets rendered whenever we add a new tool and which serves as the "API" for the website.
I've prepared a fix here: https://github.com/analysis-tools-dev/website-next/pull/74
Once this gets merged, I hope that the changes will be reflected immediately (well, after a few minutes at least) after adding a new tool.🤞

**Comment by mre** [comment]
Should be live when this turns green: https://github.com/analysis-tools-dev/website-next/actions/runs/8704215487

**Comment by mre** [comment]
It's up, but it's not pretty:
https://analysis-tools.dev/tool/composer-dependency-analyser

The reason is that I forgot to pay attention to the YAML formatting instructions.
This should fix it: https://github.com/analysis-tools-dev/static-analysis/blob/master/data/tools/composer-dependency-analyser.yml

On the plus side, we can test the automatic deployment with that, so it should be fixed in a few minutes.

**Pull request merged**
