### PR TITLE
Update tools.yml

### PR DESCRIPTION
**Pull request by sergey-wowwow**

### CODE REVIEW

**Comment by mre** [comment]
Thanks @sergey-wowwow,
also added the `security` tag. 🔒

**Comment by sergey-wowwow** [comment]
@mre 
Thanks! Is that possible to move it to the `Mobile` group? Because it's a mobile analyzer

**Comment by mre** [comment]
We don't have that granularity yet, so it shows up in both mobile and security.  Technically, this is correct but maybe we can have `mobile-security` as a separate tag in the future. Only if we know of more tools to that would category first. Otherwise the list will be quite short. 😉

**Comment by sergey-wowwow** [comment]
@mre 
But the Security category contains only one tool, Oversecured has located to the Multiple languages only category :(

**Comment by mre** [comment]
Heh, yeah that's true. The rendering for the list on Github is quite basic. Only tools which have a single tag will show up in a category. The rest gets moved to the "Multiple Languages" section. That's a bit of a trade-off because we don't want a lot of duplicates on the list. On the website, each tool shows up for each of its tags. Therefore `security` tag counts 10 entries at the moment. 😊 https://analysis-tools.dev/tag/security

**Pull request merged**
