### PR TITLE
Create simplelocalize.yml

### PR DESCRIPTION
**Pull request by jpomykala**

### CODE REVIEW

**Comment by mre** [comment]
Sorry, have to decline this as this repository only lists tools for static (code) analysis. See the definition [here](https://en.wikipedia.org/wiki/Static_program_analysis).

**Comment by jpomykala** [comment]
Ouch, sorry. I thought that value extraction in order to find unused translation keys also counts as static analysis. :)

**Comment by mre** [comment]
You have a point actually. Didn't spot the extraction of unused translation keys immediately when taking a look at the project. It's a fine line I guess. The decision of not adding it is debatable from that perspective, but I'd like to stick to it for the time being as the extraction seems to be just a part of the feature-set. Sounds like a great tool nonetheless. 😉

**Comment by jpomykala** [comment]
No problem! Thanks for you time @mre 😊

**Pull request closed without merging**
