### PR TITLE
 Added missing Salesforce tools

### PR DESCRIPTION
**Pull request by rsoesemann**
Added and enhanced tools for Salesforce-specific languages (Apex, Visualforce). Why don't they shine up in the generated README even if they are mentionen by existing tools?

### CODE REVIEW

**Comment by mre** [comment]
Hey @rsoesemann,

thanks for noticing and for the PR.
Yesterday we merged a change that puts each tool into a separate `.yml` file. This helps us with our maintenance and tooling. The downside is that your PR needs to be rebased on `master` and the changes be made in the respective files of each tool. (Perfect timing, I know.)

Not sure if you find the time for the restructuring. It shouldn't be much different, but it's still work. If not we can also take over and do the changes in your branch. Whatever you prefer. 😊 

Again thanks for the PR and sorry for the additional work.

**Comment by rsoesemann** [comment]
@mre as you saw in my many retries I am not a pro. Rebasing? Would you mind helping me or just doing this for this time?

**Comment by mre** [comment]
No worries. I merged your changes in https://github.com/analysis-tools-dev/static-analysis/commit/72ef1a1949646957934abd73979623a1f013856e. Ended up merging the changes by hand because I was already in the process of updating some tools. Thanks so much for you contributions. 😊

**Comment by rsoesemann** [comment]
Why don't I see the new tool and especially the new languages like apex on the updated README?

**Comment by mre** [comment]
Sorry for the late response.
The reason is that all the tools with the `apex` tag have other tags which puts them in the "Multiple Languages" section. It's done this way because the `README.md` would grow in size significantly.
That's one of the reasons why we built the website in the end. We can have an infinite number of sub-pages over there like https://analysis-tools.dev/tag/apex 😉

**Comment by rsoesemann** [comment]
How can people change the votes on this page? Nobody uses Fortify for Apex 😅

**Comment by mre** [comment]
Very good points.

The votes get persisted but are not updated in realtime. The reason is a tradeoff between realtime results and performance (caching, basically). We are working on a better voting system that is more realtime. Probably leveraging the new [durable objects for stateful edge services](https://blog.cloudflare.com/introducing-workers-durable-objects/) announced by Cloudflare yesterday. It's exactly what we need: realtime and consistent.
We applied for the public beta and are waiting for an invite to get this migrated over from GCP/firebase.

The other problem you mentioned are services that support many languages. They appear on more pages and are therefore collecting more votes. But not every tool is equally strong in every language. 
An easy solution would be separating the votes of each tool by tag. Another one would be to separate the "multiple language" tools from the "special purpose" tools and put them into separate groups on the tag page.
Don't know which solution I'd prefer. Feedback welcome. Guess we should move that discussion over to a separate issue, though. 😆

**Pull request closed without merging**
