### PR TITLE
Add texlab TeX LSP and linter

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by mre** [comment]
I noticed that you modified the `README.md` directly. This is a common problem and we have to make it clearer, but that this is the wrong place for edits now. 😅
The right file is `data/tools.yaml`. Can you make the change there instead, @XVilka?

**Comment by XVilka** [comment]
Yes, I will.

**Comment by XVilka** [comment]
@mre fixed.

**Comment by mre** [comment]
Great! Thank you @XVilka. 👍

**Pull request merged**
